# Generated by Django 5.2.5 on 2026-04-03 10:02

import django.db.models.deletion
import etudedossier2026.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionDossier2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_initial', models.FileField(blank=True, null=True, upload_to=etudedossier2026.models.GestionDossier2026.upinit)),
            ],
        ),
        migrations.CreateModel(
            name='SauvegardeSelection2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(default='')),
                ('ordre', models.TextField(default='')),
                ('boursier', models.BooleanField(default=False)),
                ('pasexpert', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
