# Generated by Django 4.0 on 2023-08-04 08:39

from django.db import migrations, models
import etudedossier2021.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('etudedossier2021', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionDossier2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_initial', models.FileField(blank=True, null=True, upload_to=etudedossier2021.models.GestionDossier2021.upinit)),
            ],
        ),
        migrations.RenameModel(
            old_name='SauvegardeSelection',
            new_name='SauvegardeSelection2021',
        ),
        migrations.DeleteModel(
            name='GestionDossier',
        ),
    ]
