# Generated by Django 5.2 on 2025-04-11 15:38

import django.db.models.deletion
import etudedossier2025.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnciensEleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.TextField(default='')),
                ('num_dossier', models.TextField(default='')),
                ('rne', models.TextField(default='')),
                ('prenom', models.TextField(default='')),
                ('nom', models.TextField(default='')),
                ('note_initiale', models.TextField(default='')),
                ('note_finale', models.TextField(default='')),
                ('rang', models.TextField(default='')),
                ('modif_auto', models.TextField(default='')),
                ('commentaire', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='GestionDossier2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_initial', models.FileField(blank=True, null=True, upload_to=etudedossier2025.models.GestionDossier2025.upinit)),
            ],
        ),
        migrations.CreateModel(
            name='SauvegardeSelection2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(default='')),
                ('ordre', models.TextField(default='')),
                ('boursier', models.BooleanField(default=False)),
                ('pasexpert', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
