# Generated by Django 5.2.5 on 2026-04-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudedossier2025', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnciensEleves',
        ),
    ]
