# Generated by Django 4.1.4 on 2024-04-15 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import etudedossier2024.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionDossier2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_initial', models.FileField(blank=True, null=True, upload_to=etudedossier2024.models.GestionDossier2024.upinit)),
            ],
        ),
        migrations.CreateModel(
            name='SauvegardeSelection2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(default='')),
                ('ordre', models.TextField(default='')),
                ('boursier', models.BooleanField(default=False)),
                ('pasexpert', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
