# Generated by Django 5.1 on 2025-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudedossier2024', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnciensEleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.TextField(default='')),
                ('rne', models.TextField(default='')),
                ('prenom', models.TextField(default='')),
                ('nom', models.TextField(default='')),
                ('note_initiale', models.TextField(default='')),
                ('note_finale', models.TextField(default='')),
                ('rang', models.TextField(default='')),
                ('modif_auto', models.TextField(default='')),
                ('commentaire', models.TextField(default='')),
            ],
        ),
    ]
