# Generated by Django 5.1 on 2025-04-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudedossier2024', '0002_ancienseleves'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancienseleves',
            name='num_dossier',
            field=models.TextField(default=''),
        ),
    ]
