# Generated by Django 5.1 on 2025-04-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudedossier2024', '0003_ancienseleves_num_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancienseleves',
            name='classe',
            field=models.TextField(default=''),
        ),
    ]
