# Generated by Django 4.0 on 2022-08-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('parent', models.IntegerField()),
                ('fonction', models.CharField(max_length=50)),
                ('ordre', models.IntegerField()),
                ('groupes', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
