# Generated by Django 4.0 on 2022-08-10 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='gestionnaires',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fonction',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
