# Generated by Django 4.0 on 2022-08-10 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestionmenu', '0002_menu_gestionnaires_alter_menu_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='gestionnaires',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='groupes',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
