# Generated by Django 4.0 on 2022-08-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0004_fichier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['parent', 'ordre']},
        ),
    ]
