# Generated by Django 4.0 on 2022-08-12 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionmenu', '0008_alter_fichier_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupeColles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('eleves', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreneauxColleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(blank=True, default='', max_length=20)),
                ('horaire', models.CharField(blank=True, default='', max_length=20)),
                ('salle', models.CharField(blank=True, default='', max_length=20)),
                ('matière', models.CharField(blank=True, default='', max_length=20)),
                ('numero', models.IntegerField()),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Colloscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.creneauxcolleurs')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.groupecolles')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.semaines')),
            ],
        ),
    ]
