# Generated by Django 4.0 on 2022-08-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0009_semaines_groupecolles_creneauxcolleurs_colloscope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renseignements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('année', models.IntegerField()),
                ('nomusage', models.CharField(blank=True, default='', max_length=50)),
                ('prenomusage', models.CharField(blank=True, default='', max_length=50)),
                ('naissance', models.DateField(blank=True, null=True)),
                ('tempstrajet', models.IntegerField(blank=True, null=True)),
                ('seullogement', models.BooleanField(blank=True, null=True)),
                ('motivationprepa', models.TextField(blank=True, null=True)),
                ('lyceeorigine', models.CharField(blank=True, max_length=50, null=True)),
                ('villelyceeorigine', models.CharField(blank=True, max_length=50, null=True)),
                ('professionparents', models.TextField(blank=True, null=True)),
                ('freressoeurs', models.TextField(blank=True, null=True)),
                ('calculatrice', models.CharField(blank=True, max_length=50, null=True)),
                ('accessordinateur', models.BooleanField(blank=True, null=True)),
                ('connexioninternet', models.BooleanField(blank=True, null=True)),
                ('coursconfinementmath', models.CharField(blank=True, choices=[['1', '1 :quasi inexistant'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5 : sans changement notable']], max_length=1, null=True)),
                ('coursconfinementphysique', models.CharField(blank=True, choices=[['1', '1 :quasi inexistant'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5 : sans changement notable']], max_length=1, null=True)),
                ('confinementcommentaire', models.TextField(blank=True, null=True)),
                ('notesbac', models.TextField(blank=True, null=True)),
                ('choix1', models.CharField(blank=True, choices=[['A', 'MP*'], ['B', 'MP'], ['C', 'PSI*'], ['D', 'PSI'], ['E', 'Réorientation']], max_length=1, null=True)),
                ('choix2', models.CharField(blank=True, choices=[['A', 'MP*'], ['B', 'MP'], ['C', 'PSI*'], ['D', 'PSI'], ['E', 'Réorientation']], max_length=1, null=True)),
                ('choix3', models.CharField(blank=True, choices=[['A', 'MP*'], ['B', 'MP'], ['C', 'PSI*'], ['D', 'PSI'], ['E', 'Réorientation']], max_length=1, null=True)),
                ('choix4', models.CharField(blank=True, choices=[['A', 'MP*'], ['B', 'MP'], ['C', 'PSI*'], ['D', 'PSI'], ['E', 'Réorientation']], max_length=1, null=True)),
                ('option', models.CharField(blank=True, choices=[['I', 'Info'], ['S', 'SI'], ['T', 'SI avec TP']], max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='nom',
            field=models.CharField(max_length=40),
        ),
    ]
