# Generated by Django 4.0 on 2022-08-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0010_renseignements_alter_menu_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='renseignements',
            name='année',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renseignements',
            name='nomusage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='renseignements',
            name='prenomusage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
