# Generated by Django 4.0 on 2022-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0011_divers_alter_renseignements_année_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.IntegerField(blank=True),
        ),
    ]
