# Generated by Django 4.0 on 2022-08-15 08:32

from django.db import migrations, models
import gestionmenu.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0012_alter_menu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='renseignements',
            name='pdf_parcoursup',
            field=models.FileField(blank=True, null=True, upload_to=gestionmenu.models.Renseignements.uploadpath),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
