# Generated by Django 4.0 on 2022-08-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0013_renseignements_pdf_parcoursup_alter_fichier_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renseignements',
            name='pdf_parcoursup',
        ),
        migrations.AddField(
            model_name='renseignements',
            name='pdf_parcoursup',
            field=models.ManyToManyField(to='gestionmenu.Fichier'),
        ),
    ]
