# Generated by Django 4.0 on 2022-08-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0014_remove_renseignements_pdf_parcoursup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renseignements',
            old_name='pdf_parcoursup',
            new_name='pdf',
        ),
    ]
