# Generated by Django 4.0.3 on 2022-08-26 13:13

from django.db import migrations, models
import gestionmenu.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0015_rename_pdf_parcoursup_renseignements_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgColleMath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('description', models.CharField(default='', max_length=5000)),
                ('programme', models.FileField(blank=True, null=True, upload_to=gestionmenu.models.ProgColleMath.uploadpathprog)),
                ('exercices', models.FileField(blank=True, null=True, upload_to=gestionmenu.models.ProgColleMath.uploadpathexos)),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
    ]
