# Generated by Django 4.0 on 2022-08-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0017_notescolles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notescolles',
            name='semaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.semaines'),
        ),
    ]
