# Generated by Django 4.0 on 2022-11-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0018_alter_notescolles_semaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='date_parution',
            field=models.DateField(blank=True, null=True),
        ),
    ]
