# Generated by Django 4.1.4 on 2024-04-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmenu', '0020_alter_renseignements_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renseignements',
            name='pdf',
            field=models.ManyToManyField(blank=True, to='gestionmenu.fichier'),
        ),
    ]
