# Generated by Django 4.0 on 2023-04-16 12:24

from django.db import migrations, models
import django.db.models.deletion
import etudedossier2023.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionDossier2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_initial', models.FileField(blank=True, null=True, upload_to=etudedossier2023.models.GestionDossier2023.upinit)),
            ],
        ),
        migrations.CreateModel(
            name='SauvegardeSelection2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(default='')),
                ('ordre', models.TextField(default='')),
                ('boursier', models.BooleanField(default=False)),
                ('pasexpert', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
