from .config_mail_perso import *

# EMAIL SETTINGS 

EMAIL_USE_TLS = True
EMAIL_HOST_USER = MY_EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = MY_EMAIL_HOST_PASSWORD
EMAIL_HOST = MY_EMAIL_HOST
EMAIL_PORT = MY_EMAIL_PORT
URL_COMPLETE = MY_URL_COMPLETE